[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
coord_2d = { path =  "../coord_2d" }
grid = { path = "../grid" }
utils = { path = "../utils" }
regex = { workspace = true }

[[bin]]
name = "day_1"
path = "src/day_1/main.rs"

[[bin]]
name = "day_2"
path = "src/day_2/main.rs"

[[bin]]
name = "day_3"
path = "src/day_3/main.rs"

[[bin]]
name = "day_4"
path = "src/day_4/main.rs"